title: Programming, Algorithms, Web Development etc.
author: Marcelo Martins
description: > # this means to ignore newlines until "baseurl:"
  Summer School @ USP, Web Development, Algorithms and anything else that I worked or I'm interested.

github_username:  mrezende

theme: jekyll-theme-minimal
